import { useMemo, type CSSProperties } from 'react';
import type { Resume } from '@careerforge/schema';
import { getTemplate } from '@careerforge/templates';

interface ResumePreviewProps {
  resume: Resume;
  /** Scale factor for the preview pane. Default: 0.5 (half-size).
   * The template renders at full A4 width (794px) and is scaled down
   * via CSS transform so it fits the editor sidebar without reflow. */
  scale?: number;
  className?: string;
}

const A4_WIDTH_PX = 794;
const A4_HEIGHT_PX = 1123;

/**
 * Renders a live preview of the resume using the exact same HTML that will
 * be handed to Puppeteer for PDF generation — the preview is provably
 * WYSIWYG with the export, by construction. No separate template
 * implementation for preview vs export.
 *
 * The iframe sandbox attribute allows scripts (needed for Google Fonts loading
 * inside the template) while isolating the template's CSS from the editor UI.
 * `allow-same-origin` is needed for the iframe to be readable by JS if we
 * ever want to inspect rendered content; it's safe here because the content
 * is generated by our own template functions, not user-supplied arbitrary HTML.
 */
export function ResumePreview({ resume, scale = 0.5, className = '' }: ResumePreviewProps) {
  const html = useMemo(() => {
    try {
      const template = getTemplate(resume.theme.templateId);
      return template.renderHtml(resume);
    } catch (err) {
      console.error('Template render error:', err);
      return '<html><body style="font-family:sans-serif;padding:20px;color:#666">Preview unavailable</body></html>';
    }
  }, [resume]);

  const containerStyle: CSSProperties = {
    width: A4_WIDTH_PX * scale,
    height: A4_HEIGHT_PX * scale,
    overflow: 'hidden',
    flexShrink: 0,
  };

  const iframeStyle: CSSProperties = {
    width: A4_WIDTH_PX,
    height: A4_HEIGHT_PX,
    border: 'none',
    transformOrigin: 'top left',
    transform: `scale(${scale})`,
    pointerEvents: 'none', // preview is display-only; clicks fall through to the editor
  };

  return (
    <div style={containerStyle} className={`bg-white shadow-lg rounded-sm ${className}`}>
      <iframe
        title="Resume preview"
        srcDoc={html}
        sandbox="allow-scripts allow-same-origin"
        style={iframeStyle}
        aria-label="Live resume preview"
      />
    </div>
  );
}
